before:
  hooks:
    - go mod tidy
builds:
  - skip: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
